# **LABORATORY TASK 5**

**Monique Antoinette R. Mendoza**

**DS4A**


1. Perform Standard Imports


2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.


3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.


4. Create a tensor "x" from the array above


5. Change the dtype of x from int32 to int64


6. Reshape x into a 3x2 tensor
There are several ways to do this.


7. Return the right-hand column of tensor x


8. Without changing x, return a tensor of square values of x
There are several ways to do this.


9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed.
Think about what shape it should have to permit matrix multiplication.


10. Find the matrix product of x and y.

In [ ]:
# 1 Perform Standard Imports
import torch
import numpy as np
import sys
import random
print(torch.__version__)

2.8.0+cu126


In [ ]:
# 2. Create a function called set_seed() This function sets the random seed for both NumPy and PyTorch.

def set_seed(seed: int):
    """
    Sets the seed for reproducibility.
    Parameters:
        seed (int): The seed value to use.
    """
    np.random.seed(seed)       # sets the seed for NumPy random operations
    torch.manual_seed(seed)    # sets the seed for PyTorch random operations

In [ ]:
# 3. Create a NumPy array "arr"  containing 6 random integers [0, 5) with seed = 42

set_seed(42)
arr = np.random.randint(0, 5, size=6)
print("No.3 - NumPy Array:\n", arr)


No.3 - NumPy Array:
 [3 4 2 4 4 1]


In [ ]:
# 4. Create a tensor "x" from the array above
x = torch.from_numpy(arr)
print("\nNo.4 - Tensor x (from NumPy array):\n", x)


No.4 - Tensor x (from NumPy array):
 tensor([3, 4, 2, 4, 4, 1])


In [ ]:
# 5. Change dtype of x from int32 to int64
x = x.to(torch.int64)
print("\nNo.5 - Tensor x (converted to int64):\n", x)


No.5 - Tensor x (converted to int64):
 tensor([3, 4, 2, 4, 4, 1])


In [ ]:
# 6. Reshape x into a 3x2 tensor
x = x.reshape(3, 2)
print("\nNo.6 - Tensor x reshaped to 3x2:\n", x)



No.6 - Tensor x reshaped to 3x2:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [ ]:
# 7. Return the right-hand column of tensor x - We take all rows, last column (index 1)
right_col = x[:, 1]
print("\nNo.7 - Right-hand column of x:\n", right_col)



No.7 - Right-hand column of x:
 tensor([4, 4, 1])


In [ ]:
# 8. Return tensor of square values of x without changing x itself
x_squared = x ** 2
print("\nNo.8 - Tensor of squares of x:\n", x_squared)


No.8 - Tensor of squares of x:
 tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


In [ ]:
# 9. Create tensor y - Same number of elements as x (6 total)
#    Since x is (3, 2), y should be (2, N)  so that x @ y works

set_seed(42)  # reset the seed for reproducibility
y = torch.randint(0, 5, (2, 3), dtype=torch.int64)
print("\nNo.9 - Tensor y:\n", y)


No.9 - Tensor y:
 tensor([[2, 2, 1],
        [4, 1, 0]])


In [ ]:
# 10. Find the matrix product of x and y
matmul_result = torch.matmul(x, y)
print("\nNo.10 - Matrix product of x and y:\n", matmul_result)


No.10 - Matrix product of x and y:
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
