In [1]:
# 1 Perform Standard Imports
import torch
import numpy as np
import sys
import random
print(torch.__version__)

2.8.0+cpu


In [2]:
# 2. Create a function called set_seed() This function sets the random seed for both NumPy and PyTorch.

def set_seed(seed: int):
    """
    Sets the seed for reproducibility.
    Parameters:
        seed (int): The seed value to use.
    """
    np.random.seed(seed)       # sets the seed for NumPy random operations
    torch.manual_seed(seed)    # sets the seed for PyTorch random operations

In [3]:
# 3. Create a NumPy array "arr"  containing 6 random integers [0, 5) with seed = 42

set_seed(42)
arr = np.random.randint(0, 5, size=6)
print("No.3 - NumPy Array:\n", arr)


No.3 - NumPy Array:
 [3 4 2 4 4 1]


In [4]:
# 4. Create a tensor "x" from the array above
x = torch.from_numpy(arr)
print("\nNo.4 - Tensor x (from NumPy array):\n", x)


No.4 - Tensor x (from NumPy array):
 tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


In [5]:
# 5. Change dtype of x from int32 to int64
x = x.to(torch.int64)
print("\nNo.5 - Tensor x (converted to int64):\n", x)


No.5 - Tensor x (converted to int64):
 tensor([3, 4, 2, 4, 4, 1])


In [6]:
# 6. Reshape x into a 3x2 tensor
x = x.reshape(3, 2)
print("\nNo.6 - Tensor x reshaped to 3x2:\n", x)



No.6 - Tensor x reshaped to 3x2:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [7]:
# 7. Return the right-hand column of tensor x - We take all rows, last column (index 1)
right_col = x[:, 1]
print("\nNo.7 - Right-hand column of x:\n", right_col)



No.7 - Right-hand column of x:
 tensor([4, 4, 1])


In [8]:
# 8. Return tensor of square values of x without changing x itself
x_squared = x ** 2
print("\nNo.8 - Tensor of squares of x:\n", x_squared)


No.8 - Tensor of squares of x:
 tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


In [9]:
# 9. Create tensor y - Same number of elements as x (6 total)
#    Since x is (3, 2), y should be (2, N)  so that x @ y works

set_seed(42)  # reset the seed for reproducibility
y = torch.randint(0, 5, (2, 3), dtype=torch.int64)
print("\nNo.9 - Tensor y:\n", y)


No.9 - Tensor y:
 tensor([[2, 2, 1],
        [4, 1, 0]])


In [10]:
# 10. Find the matrix product of x and y
matmul_result = torch.matmul(x, y)
print("\nNo.10 - Matrix product of x and y:\n", matmul_result)


No.10 - Matrix product of x and y:


 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
