In [1]:
import numpy as np

In [2]:
# Inputs and target
x = np.array([[1, 0, 1]])   # Input values
y = np.array([[1]])          # Target output


In [3]:
# Weights from Laboratory Task 2
W_hidden = np.array([[0.2, -0.3],
                     [0.4, 0.1],
                     [-0.5, 0.2]])

W_output = np.array([[-0.3],
                     [-0.2]])

In [4]:
# Biases
theta_hidden = np.array([[-0.4, 0.2, 0.1]]).T
b_hidden = theta_hidden[:2].T
b_output = theta_hidden[2:]

In [5]:
# Activation function: ReLU and its derivative
def relu(z):
    return np.maximum(0, z)

def relu_derivative(z):
    return (z > 0).astype(float)

# Learning rate
lr = 0.001

In [6]:
#  FORWARD PROPAGATION
Z_hidden = np.dot(x, W_hidden) + b_hidden         # Hidden layer weighted sum
A_hidden = relu(Z_hidden)                         # Hidden layer activation
Z_output = np.dot(A_hidden, W_output) + b_output  # Output layer weighted sum
y_pred = Z_output                                 # Linear output


print("Hidden layer weighted sums (Z_hidden):\n", Z_hidden)
print("\nHidden layer activations (A_hidden):\n", A_hidden)
print("\nPredicted Output (ŷ):\n", y_pred)


Hidden layer weighted sums (Z_hidden):
 [[-0.7  0.1]]

Hidden layer activations (A_hidden):
 [[0.  0.1]]

Predicted Output (ŷ):
 [[0.08]]


In [7]:
# Compute Error
E = 0.5 * (y - y_pred)**2  # Error
print("\nError (E):\n", E)


Error (E):
 [[0.4232]]


In [8]:
# Derivative of error w.r.t output
dE_dy = -(y - y_pred)

# Gradient for output layer weights
dE_dW_output = np.dot(A_hidden.T, dE_dy)


In [9]:
# Gradient for hidden layer
dE_dA_hidden = np.dot(dE_dy, W_output.T)
dA_dZ_hidden = relu_derivative(Z_hidden)
dE_dZ_hidden = dE_dA_hidden * dA_dZ_hidden
dE_dW_hidden = np.dot(x.T, dE_dZ_hidden)

In [10]:
#  UPDATE WEIGHTS
W_output -= lr * dE_dW_output
W_hidden -= lr * dE_dW_hidden

print("\nUpdated Hidden Weights:\n", W_hidden)
print("\nUpdated Output Weights:\n", W_output)


Updated Hidden Weights:
 [[ 0.2      -0.300184]
 [ 0.4       0.1     ]
 [-0.5       0.199816]]

Updated Output Weights:
 [[-0.3     ]
 [-0.199908]]
